/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinic_managment;
import java.awt.Toolkit;
import java.text.*;
import java.awt.print.*;
import javafx.print.Printer;
import javax.swing.JTextArea;

/**
 *
 * @author youss
 */
public class Visit_Report extends javax.swing.JFrame {

    /**
     * Creates new form Visit_Report
     */
    public Visit_Report() {
        initComponents();
    icon();
    }
    private void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FormName = new javax.swing.JLabel();
        FormNotes = new javax.swing.JLabel();
        FormDrugs = new javax.swing.JLabel();
        FormDiagnosis = new javax.swing.JLabel();
        FormDOV = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        diagnosisA = new javax.swing.JTextArea();
        NotesA = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        DrugsA = new javax.swing.JTextArea();
        DateA = new javax.swing.JTextField();
        nameA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DOBAdd = new javax.swing.JTextField();
        invest = new javax.swing.JLabel();
        investA = new javax.swing.JScrollPane();
        investA1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(647, 690));
        setMinimumSize(new java.awt.Dimension(647, 690));
        setPreferredSize(new java.awt.Dimension(647, 690));
        getContentPane().setLayout(null);

        FormName.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        FormName.setForeground(new java.awt.Color(255, 255, 255));
        FormName.setText("Name:");
        getContentPane().add(FormName);
        FormName.setBounds(10, 20, 95, 30);

        FormNotes.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        FormNotes.setForeground(new java.awt.Color(255, 255, 255));
        FormNotes.setText("History");
        getContentPane().add(FormNotes);
        FormNotes.setBounds(10, 60, 95, 30);

        FormDrugs.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        FormDrugs.setForeground(new java.awt.Color(255, 255, 255));
        FormDrugs.setText("Treatment:");
        getContentPane().add(FormDrugs);
        FormDrugs.setBounds(10, 330, 60, 30);

        FormDiagnosis.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        FormDiagnosis.setForeground(new java.awt.Color(255, 255, 255));
        FormDiagnosis.setText("Clinical Examination:");
        getContentPane().add(FormDiagnosis);
        FormDiagnosis.setBounds(10, 190, 130, 30);

        FormDOV.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        FormDOV.setForeground(new java.awt.Color(255, 255, 255));
        FormDOV.setText("Date of Visit: ");
        getContentPane().add(FormDOV);
        FormDOV.setBounds(10, 610, 95, 30);

        diagnosisA.setEditable(false);
        diagnosisA.setBackground(new java.awt.Color(204, 204, 204));
        diagnosisA.setColumns(20);
        diagnosisA.setRows(5);
        jScrollPane1.setViewportView(diagnosisA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 190, 490, 132);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        NotesA.setViewportView(jTextArea2);

        getContentPane().add(NotesA);
        NotesA.setBounds(130, 60, 490, 123);

        DrugsA.setEditable(false);
        DrugsA.setBackground(new java.awt.Color(204, 204, 204));
        DrugsA.setColumns(20);
        DrugsA.setRows(5);
        jScrollPane3.setViewportView(DrugsA);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(130, 330, 490, 120);

        DateA.setEditable(false);
        DateA.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(DateA);
        DateA.setBounds(130, 610, 170, 30);

        nameA.setEditable(false);
        nameA.setBackground(new java.awt.Color(204, 204, 204));
        nameA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameAActionPerformed(evt);
            }
        });
        getContentPane().add(nameA);
        nameA.setBounds(130, 20, 170, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date Of Birth");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 20, 70, 30);

        DOBAdd.setEditable(false);
        DOBAdd.setBackground(new java.awt.Color(204, 204, 204));
        DOBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBAddActionPerformed(evt);
            }
        });
        getContentPane().add(DOBAdd);
        DOBAdd.setBounds(390, 20, 160, 30);

        invest.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        invest.setForeground(new java.awt.Color(255, 255, 255));
        invest.setText("Investigation:");
        getContentPane().add(invest);
        invest.setBounds(10, 460, 110, 30);

        investA1.setEditable(false);
        investA1.setBackground(new java.awt.Color(204, 204, 204));
        investA1.setColumns(20);
        investA1.setRows(5);
        investA.setViewportView(investA1);

        getContentPane().add(investA);
        investA.setBounds(130, 460, 490, 130);

        jButton1.setText("Go To Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 600, 130, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_managment/resources/10-106985_simple-backgrounds-for-presentations.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-260, -90, 1260, 810);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DOBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

          String treatment= DrugsA.getText();
          String name= nameA.getText();
          String date= DateA.getText();
          new prescription(treatment,name,date).setVisible(true);
          setVisible(false);
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visit_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visit_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visit_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visit_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visit_Report().setVisible(true);
            }
        });
        
        
       //nameA.setEnabled(false);
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField DOBAdd;
    public javax.swing.JTextField DateA;
    public javax.swing.JTextArea DrugsA;
    private javax.swing.JLabel FormDOV;
    private javax.swing.JLabel FormDiagnosis;
    private javax.swing.JLabel FormDrugs;
    private javax.swing.JLabel FormName;
    private javax.swing.JLabel FormNotes;
    private javax.swing.JScrollPane NotesA;
    public javax.swing.JTextArea diagnosisA;
    private javax.swing.JLabel invest;
    private javax.swing.JScrollPane investA;
    public javax.swing.JTextArea investA1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextArea jTextArea2;
    public javax.swing.JTextField nameA;
    // End of variables declaration//GEN-END:variables
}
